### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by medallyon** [Medallyon/SkyCity#6]
- [x] Player
  - [x] Scalar Movement
  - [x] 3D Spacial Navigation (up, down, left, right)
  - [x] Speed Boost
  - [x] Shooting mechanic
- [x] City
  - [x] Grid Generation
  - [x] Random Prefab per object
    - [ ] At least 3 different meshes
  - [x] Accurate NavMesh Generation
- [x] Enemies
  - [x] Objective: Kill `X` enemies to win the game
  - [x] Simple Moving AI along generated NavMesh
  - [ ] (Optional) Fights back when attacked
  - [x] At least 2 different meshes/prefabs for enemies
- [x] Scenes
  - [x] Main Menu
  - [x] Pause Menu
  - [x] Post-Game Scene
- [x] Audio
  - [x] BG Music
  - [x] Engine Sounds
  - [x] Laser Shot
  - [x] Laser Impact
  - [x] Explosion
- [x] Other
  - [x] Space Sky Texture
  - [x] Particle Systems
    - [x] Explosions
    - [x] Hit Effects
    - [x] Engine Trails
